- name: install nginx
  hosts: web
  become: yes  # means root user
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: installed
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enable: yes 